<?php
/**
 * @file
 * Influxis module file
 * Module handles uploading viewing and deleting files from Influxis API
 * Most hooks are grouped with similar hooks in separate files 
 * this file includes those files and provides a couple of additional hooks
 */

module_load_include('inc', 'influxis', 'influxis.field');
module_load_include('inc', 'influxis', 'influxis.admin');
module_load_include('inc', 'influxis', 'influxis.views');
module_load_include('inc', 'influxis', 'influxis.helpers');

/**
 * hook_cron()
*/
function influxis_cron() {
  watchdog("influxis", "running influsix cron");
  _influxis_update_videos();
}

/**
 * hook_menu
 */
function influxis_menu() {
  $items = array();
  $admin_file = 'influxis.admin.inc';

  // To level influxis menu, pulls same form as account settings.
  $items['admin/config/media/influxis'] = array(
    'title' => 'Influxis',
    'description' => 'Allows the user to configure the Influxis settings',
    'file' => $admin_file,
    'page callback' => 'influxis_settings_page',
    'access arguments' => array('administrator influxis settings'),
  );
  // Account settings admin form.
  $items['admin/config/media/influxis/account'] = array(
    'title' => 'Influxis Account Settings',
    'description' => 'Settings for Influxis module',
    'file' => $admin_file,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('influxis_account_settings'),
    'access arguments' => array('administrator influxis settings'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );
  // Encode account settings.
  $items['admin/config/media/influxis/encode'] = array(
    'title' => 'Influxis Encoding Settings',
    'description' => 'Encode Settings for Influxis module',
    'file' => $admin_file,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('influxis_encoding_settings'),
    'access arguments' => array('administrator influxis settings'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  // Status admin page.
  $items['admin/config/media/influxis/status'] = array(
    'title' => 'Influxis Status',
    'description' => 'Status of all the jobs with Influxis',
    'file' => $admin_file,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('influxis_status_form'),
    'access arguments' => array('administrator influxis settings'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1
  );
  return $items;
}


/**
 * hook_permission()
 */
function influxis_permission() {
  return array(
    'administrator influxis settings' => array(
      'title' => t('Administer Influxis'),
    )
  );
}
