<?php
/**
 * @file
 * Influxis module file.
 *
 * Module handles uploading viewing and deleting files from Influxis API.
 * Most hooks are grouped with similar hooks in separate files.
 */

module_load_include('inc', 'influxis', 'influxis.field');
module_load_include('inc', 'influxis', 'influxis.admin');
module_load_include('inc', 'influxis', 'influxis.views');
module_load_include('inc', 'influxis', 'influxis.helpers');

/**
 * Implements hook_cron().
 */
function influxis_cron() {
  watchdog("influxis", "running influis cron");
  _influxis_update_videos();
}

/**
 * Implements hook_menu().
 */
function influxis_menu() {
  $items = array();
  $admin_file = 'influxis.admin.inc';

  // To level influxis menu, pulls same form as account settings.
  $items['admin/config/media/influxis'] = array(
    'title' => 'Influxis',
    'description' => 'Allows the user to configure the Influxis settings',
    'file' => $admin_file,
    'page callback' => 'influxis_settings_page',
    'access arguments' => array('administrator influxis settings'),
  );
  // Account settings admin form.
  $items['admin/config/media/influxis/account'] = array(
    'title' => 'Influxis Account Settings',
    'description' => 'Settings for Influxis module',
    'file' => $admin_file,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('influxis_account_settings'),
    'access arguments' => array('administrator influxis settings'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );
  // Encode account settings.
  $items['admin/config/media/influxis/encode'] = array(
    'title' => 'Influxis Encoding Settings',
    'description' => 'Encode Settings for Influxis module',
    'file' => $admin_file,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('influxis_encoding_settings'),
    'access arguments' => array('administrator influxis settings'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  // Status admin page.
  $items['admin/config/media/influxis/status'] = array(
    'title' => 'Influxis Status',
    'description' => 'Status of all the jobs with Influxis',
    'file' => $admin_file,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('influxis_status_form'),
    'access arguments' => array('administrator influxis settings'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  return $items;
}


/**
 * Implements hook_permission().
 */
function influxis_permission() {
  return array(
    'administrator influxis settings' => array(
      'title' => t('Administer Influxis'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function influxis_theme() {
	return array(
			'influxis_form_table' => array(
					'render element' => 'form',
			),
	);
}

/**
 * Implements hook_help().
 */
function influxis_help($path, $arg) {
  switch ($path) {
    case 'admin/help#influxis':
      $output = '';
      $output .= '<h3>' . "INTRODUCTION" . '</h3>';
      $output .= '<p>' . "The influxis module allows videos to be uploaded to the influxis api using Drupal.  Videos are played back using flowplayer once they have completed the encoding process." . '</p>';
      $output .= '<h3>' . "REQUIREMENTS" . '</h3>';
      $output .= '<p>' . "This module requires the following modules:";
      $output .= '<ul><li>' . "Flowplayer5 (https://www.drupal.org/project/flowplayer5)" . '</li>';
      $output .= '<li>' . " Password encryption for influxis uses php mcrypt extension to be installed" . '</li>';
      $output .= "</ul></p>";
      $output .= '<h3>Configuration</h3>';
      $output .= '<p>Configure user permissions in Administration => People => Permissions:';
      $output .= '<ul><li>Administer Influxis:   Users in roles with the "Administer Influxis" permission will see the the influxis configuration page under Administration => Configuration => Media => Influxis .</li>';
      $output .= '<li>Configure all the encoding settings sent in the request to influxis at Administration => Configuration => Media => Influxis</li>';
      $output .= '<li>Username, password, API url and video url must be set. </li>';
      $output .= '<li>Video url is the http version of the RTMP/FMS url in account settings on influxis.com</li></ul><p>';

      return check_markup($output, 'full_html');
  }
}
